package:
  name: nbdevminimum
  version: 0.0.9
source:
  sha256: 6b3ab37269a6ab6eab642efb58d16111ad149d0ac989becc75c02fc08c7d40d4
  url: https://files.pythonhosted.org/packages/08/74/6eb7fb6adb8e63ffc241fe47c802424fa9a00a291cd3e915094c8068ba1f/nbdevminimum-0.0.9.tar.gz
about:
  dev_url: https://Isaac-Flath.github.io
  doc_url: https://Isaac-Flath.github.io
  home: https://Isaac-Flath.github.io
  license: Apache Software
  license_family: APACHE
  summary: Minimal export of notebooks nbdev style for one-off projects that don't
    need to be a full library
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Isaac-Flath
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - nbdevminimum
