package:
  name: nbdevminimum
  version: 0.1.0
source:
  sha256: 49007b150fa22e192a62ddcaf645f1a02aae69d345a9c93d9eb680a98f8279d3
  url: https://files.pythonhosted.org/packages/53/01/a16c5e72f7ec1e463f51b49ee837afbd5378b09195b7a0a19f856f9d63ca/nbdevminimum-0.1.0.tar.gz
about:
  dev_url: https://Isaac-Flath.github.io
  doc_url: https://Isaac-Flath.github.io
  home: https://Isaac-Flath.github.io
  license: Apache Software
  license_family: APACHE
  summary: Minimal export of notebooks nbdev style for one-off projects that don't
    need to be a full library
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - Isaac-Flath
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - nbdevminimum
